name: unused_assets_removal
description: >
  A CLI tool to detect and optionally delete unused asset files in your Flutter project, helping you reduce app size and clean up unnecessary files.
version: 0.0.1
homepage: https://github.com/3boodev/unused_assets_removal
repository: https://github.com/3boodev/unused_assets_removal

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.0

executables:
  unused_assets_removal: unused_assets_removal

# Optional: You can define topics (for pub.dev discoverability)
topics:
  - flutter
  - cli
  - assets
  - cleanup
  - optimization


# Exclude any unnecessary files from the package
false_secrets:
  - example/*
  - test/assets/*
flutter:
  assets:
    - assets/images/